# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

event_writer <- function(file) {
    .Call(`_tfevents_event_writer`, file)
}

flush_event_writer <- function(writer) {
    invisible(.Call(`_tfevents_flush_event_writer`, writer))
}

write_scalar <- function(writer, name, data, step, description, display_name) {
    .Call(`_tfevents_write_scalar`, writer, name, data, step, description, display_name)
}

unload_protobuf <- function() {
    invisible(.Call(`_tfevents_unload_protobuf`))
}

create_event_file_iterator <- function(path) {
    .Call(`_tfevents_create_event_file_iterator`, path)
}

event_file_iterator_next <- function(iter) {
    .Call(`_tfevents_event_file_iterator_next`, iter)
}

event_file_iterator_collect <- function(path) {
    .Call(`_tfevents_event_file_iterator_collect`, path)
}

